//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobilis
{
	
	
	public partial class Resource
	{
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0d0000
			public const int entries_list_preference = 2131558400;
			
			// aapt resource value: 0x7f0d0001
			public const int entryvalues_list_preference = 2131558401;
			
			// aapt resource value: 0x7f0d0002
			public const int locations = 2131558402;
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010039
			public const int absForceOverflow = 2130772025;
			
			// aapt resource value: 0x7f01000e
			public const int actionBarDivider = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int actionBarItemBackground = 2130771983;
			
			// aapt resource value: 0x7f01000d
			public const int actionBarSize = 2130771981;
			
			// aapt resource value: 0x7f01000b
			public const int actionBarSplitStyle = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int actionBarStyle = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int actionBarTabBarStyle = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int actionBarTabStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int actionBarTabTextStyle = 2130771976;
			
			// aapt resource value: 0x7f01000c
			public const int actionBarWidgetTheme = 2130771980;
			
			// aapt resource value: 0x7f01002b
			public const int actionButtonStyle = 2130772011;
			
			// aapt resource value: 0x7f01002a
			public const int actionDropDownStyle = 2130772010;
			
			// aapt resource value: 0x7f010010
			public const int actionMenuTextAppearance = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int actionMenuTextColor = 2130771985;
			
			// aapt resource value: 0x7f010014
			public const int actionModeBackground = 2130771988;
			
			// aapt resource value: 0x7f010013
			public const int actionModeCloseButtonStyle = 2130771987;
			
			// aapt resource value: 0x7f010016
			public const int actionModeCloseDrawable = 2130771990;
			
			// aapt resource value: 0x7f010018
			public const int actionModePopupWindowStyle = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int actionModeShareDrawable = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int actionModeSplitBackground = 2130771989;
			
			// aapt resource value: 0x7f010012
			public const int actionModeStyle = 2130771986;
			
			// aapt resource value: 0x7f010009
			public const int actionOverflowButtonStyle = 2130771977;
			
			// aapt resource value: 0x7f010030
			public const int actionSpinnerItemStyle = 2130772016;
			
			// aapt resource value: 0x7f010038
			public const int activatedBackgroundIndicator = 2130772024;
			
			// aapt resource value: 0x7f010037
			public const int activityChooserViewStyle = 2130772023;
			
			// aapt resource value: 0x7f010002
			public const int background = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int backgroundSplit = 2130771971;
			
			// aapt resource value: 0x7f010040
			public const int backgroundStacked = 2130772032;
			
			// aapt resource value: 0x7f010019
			public const int buttonStyleSmall = 2130771993;
			
			// aapt resource value: 0x7f010041
			public const int customNavigationLayout = 2130772033;
			
			// aapt resource value: 0x7f01003b
			public const int displayOptions = 2130772027;
			
			// aapt resource value: 0x7f010005
			public const int divider = 2130771973;
			
			// aapt resource value: 0x7f010029
			public const int dividerVertical = 2130772009;
			
			// aapt resource value: 0x7f01002d
			public const int dropDownListViewStyle = 2130772013;
			
			// aapt resource value: 0x7f01002f
			public const int dropdownListPreferredItemHeight = 2130772015;
			
			// aapt resource value: 0x7f010050
			public const int expandActivityOverflowButtonDrawable = 2130772048;
			
			// aapt resource value: 0x7f01004a
			public const int headerBackground = 2130772042;
			
			// aapt resource value: 0x7f010004
			public const int height = 2130771972;
			
			// aapt resource value: 0x7f01002c
			public const int homeAsUpIndicator = 2130772012;
			
			// aapt resource value: 0x7f010042
			public const int homeLayout = 2130772034;
			
			// aapt resource value: 0x7f010048
			public const int horizontalDivider = 2130772040;
			
			// aapt resource value: 0x7f01003e
			public const int icon = 2130772030;
			
			// aapt resource value: 0x7f010044
			public const int indeterminateProgressStyle = 2130772036;
			
			// aapt resource value: 0x7f01004f
			public const int initialActivityCount = 2130772047;
			
			// aapt resource value: 0x7f01004b
			public const int itemBackground = 2130772043;
			
			// aapt resource value: 0x7f01004d
			public const int itemIconDisabledAlpha = 2130772045;
			
			// aapt resource value: 0x7f010046
			public const int itemPadding = 2130772038;
			
			// aapt resource value: 0x7f010047
			public const int itemTextAppearance = 2130772039;
			
			// aapt resource value: 0x7f010036
			public const int listPopupWindowStyle = 2130772022;
			
			// aapt resource value: 0x7f010023
			public const int listPreferredItemHeightSmall = 2130772003;
			
			// aapt resource value: 0x7f010024
			public const int listPreferredItemPaddingLeft = 2130772004;
			
			// aapt resource value: 0x7f010025
			public const int listPreferredItemPaddingRight = 2130772005;
			
			// aapt resource value: 0x7f01003f
			public const int logo = 2130772031;
			
			// aapt resource value: 0x7f01003a
			public const int navigationMode = 2130772026;
			
			// aapt resource value: 0x7f01002e
			public const int popupMenuStyle = 2130772014;
			
			// aapt resource value: 0x7f01004e
			public const int preserveIconSpacing = 2130772046;
			
			// aapt resource value: 0x7f010045
			public const int progressBarPadding = 2130772037;
			
			// aapt resource value: 0x7f010043
			public const int progressBarStyle = 2130772035;
			
			// aapt resource value: 0x7f010022
			public const int spinnerDropDownItemStyle = 2130772002;
			
			// aapt resource value: 0x7f010021
			public const int spinnerItemStyle = 2130772001;
			
			// aapt resource value: 0x7f01003d
			public const int subtitle = 2130772029;
			
			// aapt resource value: 0x7f010001
			public const int subtitleTextStyle = 2130771969;
			
			// aapt resource value: 0x7f01001b
			public const int textAppearanceLargePopupMenu = 2130771995;
			
			// aapt resource value: 0x7f010026
			public const int textAppearanceListItemSmall = 2130772006;
			
			// aapt resource value: 0x7f01001d
			public const int textAppearanceSmall = 2130771997;
			
			// aapt resource value: 0x7f01001c
			public const int textAppearanceSmallPopupMenu = 2130771996;
			
			// aapt resource value: 0x7f01001e
			public const int textColorPrimary = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int textColorPrimaryDisableOnly = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int textColorPrimaryInverse = 2130772000;
			
			// aapt resource value: 0x7f01003c
			public const int title = 2130772028;
			
			// aapt resource value: 0x7f010000
			public const int titleTextStyle = 2130771968;
			
			// aapt resource value: 0x7f010049
			public const int verticalDivider = 2130772041;
			
			// aapt resource value: 0x7f010032
			public const int windowActionBar = 2130772018;
			
			// aapt resource value: 0x7f010033
			public const int windowActionBarOverlay = 2130772019;
			
			// aapt resource value: 0x7f010034
			public const int windowActionModeOverlay = 2130772020;
			
			// aapt resource value: 0x7f01004c
			public const int windowAnimationStyle = 2130772044;
			
			// aapt resource value: 0x7f01001a
			public const int windowContentOverlay = 2130771994;
			
			// aapt resource value: 0x7f010027
			public const int windowMinWidthMajor = 2130772007;
			
			// aapt resource value: 0x7f010028
			public const int windowMinWidthMinor = 2130772008;
			
			// aapt resource value: 0x7f010031
			public const int windowNoTitle = 2130772017;
			
			// aapt resource value: 0x7f010035
			public const int windowSplitActionBar = 2130772021;
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f070000
			public const int abs__action_bar_embed_tabs = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int abs__action_bar_expanded_action_views_exclusive = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int abs__config_actionMenuItemAllCaps = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int abs__config_allowActionMenuItemTextWithIcon = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int abs__config_showMenuShortcutsWhenKeyboardPresent = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int abs__split_action_bar_is_narrow = 2131165185;
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080000
			public const int abs__background_holo_dark = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int abs__background_holo_light = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int abs__bright_foreground_disabled_holo_dark = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int abs__bright_foreground_disabled_holo_light = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int abs__bright_foreground_holo_dark = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int abs__bright_foreground_holo_light = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int abs__bright_foreground_inverse_holo_dark = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int abs__bright_foreground_inverse_holo_light = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int abs__holo_blue_light = 2131230728;
			
			// aapt resource value: 0x7f080015
			public const int abs__primary_text_disable_only_holo_dark = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int abs__primary_text_disable_only_holo_light = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int abs__primary_text_holo_dark = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int abs__primary_text_holo_light = 2131230744;
			
			// aapt resource value: 0x7f080011
			public const int action_bar_active = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int action_bar_idle = 2131230736;
			
			// aapt resource value: 0x7f08000b
			public const int course_list_idle = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int course_list_pressed = 2131230732;
			
			// aapt resource value: 0x7f08000e
			public const int list_divider = 2131230734;
			
			// aapt resource value: 0x7f080014
			public const int post_count = 2131230740;
			
			// aapt resource value: 0x7f080012
			public const int post_idle = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int post_selected = 2131230739;
			
			// aapt resource value: 0x7f08000a
			public const int text_color = 2131230730;
			
			// aapt resource value: 0x7f08000f
			public const int text_white_color = 2131230735;
			
			// aapt resource value: 0x7f08000d
			public const int white = 2131230733;
			
			// aapt resource value: 0x7f080009
			public const int yellow_highlight = 2131230729;
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090001
			public const int abs__action_bar_default_height = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int abs__action_bar_icon_vertical_padding = 2131296258;
			
			// aapt resource value: 0x7f090006
			public const int abs__action_bar_subtitle_bottom_margin = 2131296262;
			
			// aapt resource value: 0x7f090004
			public const int abs__action_bar_subtitle_text_size = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int abs__action_bar_subtitle_top_margin = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int abs__action_bar_title_text_size = 2131296259;
			
			// aapt resource value: 0x7f090007
			public const int abs__action_button_min_width = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int abs__alert_dialog_title_height = 2131296264;
			
			// aapt resource value: 0x7f090000
			public const int abs__config_prefDialogWidth = 2131296256;
			
			// aapt resource value: 0x7f090009
			public const int abs__dialog_min_width_major = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int abs__dialog_min_width_minor = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int action_button_min_width = 2131296267;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020077
			public const int ab_bg_black = 2130837623;
			
			// aapt resource value: 0x7f020000
			public const int abs__ab_bottom_solid_dark_holo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int abs__ab_bottom_solid_inverse_holo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int abs__ab_bottom_solid_light_holo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int abs__ab_bottom_transparent_dark_holo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int abs__ab_bottom_transparent_light_holo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int abs__ab_share_pack_holo_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int abs__ab_share_pack_holo_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int abs__ab_solid_dark_holo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int abs__ab_solid_light_holo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int abs__ab_solid_shadow_holo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int abs__ab_stacked_solid_dark_holo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int abs__ab_stacked_solid_light_holo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int abs__ab_stacked_transparent_dark_holo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int abs__ab_stacked_transparent_light_holo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int abs__ab_transparent_dark_holo = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int abs__ab_transparent_light_holo = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int abs__activated_background_holo_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int abs__activated_background_holo_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int abs__btn_cab_done_default_holo_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int abs__btn_cab_done_default_holo_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int abs__btn_cab_done_focused_holo_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int abs__btn_cab_done_focused_holo_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int abs__btn_cab_done_holo_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int abs__btn_cab_done_holo_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int abs__btn_cab_done_pressed_holo_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int abs__btn_cab_done_pressed_holo_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int abs__cab_background_bottom_holo_dark = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int abs__cab_background_bottom_holo_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int abs__cab_background_top_holo_dark = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int abs__cab_background_top_holo_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int abs__dialog_full_holo_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int abs__dialog_full_holo_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int abs__ic_ab_back_holo_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int abs__ic_ab_back_holo_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int abs__ic_cab_done_holo_dark = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int abs__ic_cab_done_holo_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int abs__ic_menu_moreoverflow_holo_dark = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int abs__ic_menu_moreoverflow_holo_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int abs__ic_menu_moreoverflow_normal_holo_dark = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int abs__ic_menu_moreoverflow_normal_holo_light = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int abs__ic_menu_share_holo_dark = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int abs__ic_menu_share_holo_light = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int abs__item_background_holo_dark = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int abs__item_background_holo_light = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int abs__list_activated_holo = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int abs__list_divider_holo_dark = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int abs__list_divider_holo_light = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int abs__list_focused_holo = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int abs__list_longpressed_holo = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int abs__list_pressed_holo_dark = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int abs__list_pressed_holo_light = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int abs__list_selector_background_transition_holo_dark = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int abs__list_selector_background_transition_holo_light = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int abs__list_selector_disabled_holo_dark = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int abs__list_selector_disabled_holo_light = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int abs__list_selector_holo_dark = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int abs__list_selector_holo_light = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int abs__menu_dropdown_panel_holo_dark = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int abs__menu_dropdown_panel_holo_light = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int abs__progress_bg_holo_dark = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int abs__progress_bg_holo_light = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int abs__progress_horizontal_holo_dark = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int abs__progress_horizontal_holo_light = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int abs__progress_medium_holo = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int abs__progress_primary_holo_dark = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int abs__progress_primary_holo_light = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int abs__progress_secondary_holo_dark = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int abs__progress_secondary_holo_light = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int abs__spinner_48_inner_holo = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int abs__spinner_48_outer_holo = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int abs__spinner_ab_default_holo_dark = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int abs__spinner_ab_default_holo_light = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int abs__spinner_ab_disabled_holo_dark = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int abs__spinner_ab_disabled_holo_light = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int abs__spinner_ab_focused_holo_dark = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int abs__spinner_ab_focused_holo_light = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int abs__spinner_ab_holo_dark = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int abs__spinner_ab_holo_light = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int abs__spinner_ab_pressed_holo_dark = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int abs__spinner_ab_pressed_holo_light = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int abs__tab_indicator_ab_holo = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int abs__tab_selected_focused_holo = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int abs__tab_selected_holo = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int abs__tab_selected_pressed_holo = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int abs__tab_unselected_pressed_holo = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int action_expand = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int action_favorite_empty = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int action_favorite_marked = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int action_favorite_unmarked = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int action_info = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int action_menu = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int action_playback = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int action_reply = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int action_reply_forum = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int bg_striped = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int bg_striped_img = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int bg_striped_split = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int bg_striped_split_img = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int course_list_selector = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int ic_compose = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int ic_compose_inverse = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int ic_launcher_settings = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int ic_magnifying_glass = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int ic_refresh = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int ic_refresh_inverse = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int ic_search = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int ic_search_inverse = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int ic_title_share_default = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int Icon = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int login_gradient = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int logo_solar = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int no_picture = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int playback_next = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int playback_pause = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int playback_play = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int playback_previous = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int playback_stop = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int refresh_button = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int stock_person = 2130837622;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060022
			public const int abs__action_bar = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int abs__action_bar_container = 2131099681;
			
			// aapt resource value: 0x7f060011
			public const int abs__action_bar_subtitle = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int abs__action_bar_title = 2131099664;
			
			// aapt resource value: 0x7f060023
			public const int abs__action_context_bar = 2131099683;
			
			// aapt resource value: 0x7f06000c
			public const int abs__action_menu_divider = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int abs__action_menu_presenter = 2131099661;
			
			// aapt resource value: 0x7f060026
			public const int abs__action_mode_bar = 2131099686;
			
			// aapt resource value: 0x7f060025
			public const int abs__action_mode_bar_stub = 2131099685;
			
			// aapt resource value: 0x7f060014
			public const int abs__action_mode_close_button = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int abs__activity_chooser_view_content = 2131099669;
			
			// aapt resource value: 0x7f06001e
			public const int abs__checkbox = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int abs__content = 2131099677;
			
			// aapt resource value: 0x7f060018
			public const int abs__default_activity_button = 2131099672;
			
			// aapt resource value: 0x7f060016
			public const int abs__expand_activities_button = 2131099670;
			
			// aapt resource value: 0x7f06000a
			public const int abs__home = 2131099658;
			
			// aapt resource value: 0x7f06001a
			public const int abs__icon = 2131099674;
			
			// aapt resource value: 0x7f060017
			public const int abs__image = 2131099671;
			
			// aapt resource value: 0x7f060012
			public const int abs__imageButton = 2131099666;
			
			// aapt resource value: 0x7f060019
			public const int abs__list_item = 2131099673;
			
			// aapt resource value: 0x7f06000e
			public const int abs__progress_circular = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int abs__progress_horizontal = 2131099663;
			
			// aapt resource value: 0x7f060020
			public const int abs__radio = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int abs__shortcut = 2131099679;
			
			// aapt resource value: 0x7f060024
			public const int abs__split_action_bar = 2131099684;
			
			// aapt resource value: 0x7f060013
			public const int abs__textButton = 2131099667;
			
			// aapt resource value: 0x7f06001b
			public const int abs__title = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int abs__titleDivider = 2131099676;
			
			// aapt resource value: 0x7f06000b
			public const int abs__up = 2131099659;
			
			// aapt resource value: 0x7f060052
			public const int action_bar_footer = 2131099730;
			
			// aapt resource value: 0x7f06004f
			public const int blue_line = 2131099727;
			
			// aapt resource value: 0x7f060051
			public const int bunch_of_text = 2131099729;
			
			// aapt resource value: 0x7f06005e
			public const int button = 2131099742;
			
			// aapt resource value: 0x7f060028
			public const int cancel = 2131099688;
			
			// aapt resource value: 0x7f060069
			public const int details = 2131099753;
			
			// aapt resource value: 0x7f060047
			public const int disable = 2131099719;
			
			// aapt resource value: 0x7f060009
			public const int disableHome = 2131099657;
			
			// aapt resource value: 0x7f06002c
			public const int display_actionbar_hide = 2131099692;
			
			// aapt resource value: 0x7f06002b
			public const int display_actionbar_show = 2131099691;
			
			// aapt resource value: 0x7f06003b
			public const int display_custom_hide = 2131099707;
			
			// aapt resource value: 0x7f06003a
			public const int display_custom_show = 2131099706;
			
			// aapt resource value: 0x7f060041
			public const int display_home_as_up_hide = 2131099713;
			
			// aapt resource value: 0x7f060040
			public const int display_home_as_up_show = 2131099712;
			
			// aapt resource value: 0x7f06003d
			public const int display_home_hide = 2131099709;
			
			// aapt resource value: 0x7f06003c
			public const int display_home_show = 2131099708;
			
			// aapt resource value: 0x7f060045
			public const int display_iprogress_hide = 2131099717;
			
			// aapt resource value: 0x7f060044
			public const int display_iprogress_show = 2131099716;
			
			// aapt resource value: 0x7f060034
			public const int display_items_add = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int display_items_clear = 2131099701;
			
			// aapt resource value: 0x7f06003f
			public const int display_logo_hide = 2131099711;
			
			// aapt resource value: 0x7f06003e
			public const int display_logo_show = 2131099710;
			
			// aapt resource value: 0x7f060043
			public const int display_progress_hide = 2131099715;
			
			// aapt resource value: 0x7f060042
			public const int display_progress_show = 2131099714;
			
			// aapt resource value: 0x7f060039
			public const int display_subtitle_hide = 2131099705;
			
			// aapt resource value: 0x7f060038
			public const int display_subtitle_show = 2131099704;
			
			// aapt resource value: 0x7f060030
			public const int display_tab_add = 2131099696;
			
			// aapt resource value: 0x7f060032
			public const int display_tab_remove = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int display_tab_remove_all = 2131099699;
			
			// aapt resource value: 0x7f060031
			public const int display_tab_select = 2131099697;
			
			// aapt resource value: 0x7f060037
			public const int display_title_hide = 2131099703;
			
			// aapt resource value: 0x7f060036
			public const int display_title_show = 2131099702;
			
			// aapt resource value: 0x7f060046
			public const int enable = 2131099718;
			
			// aapt resource value: 0x7f060065
			public const int expand = 2131099749;
			
			// aapt resource value: 0x7f06004d
			public const int footer = 2131099725;
			
			// aapt resource value: 0x7f06004e
			public const int footer_text = 2131099726;
			
			// aapt resource value: 0x7f060054
			public const int forum_range = 2131099732;
			
			// aapt resource value: 0x7f060053
			public const int forum_title = 2131099731;
			
			// aapt resource value: 0x7f06005c
			public const int go = 2131099740;
			
			// aapt resource value: 0x7f060062
			public const int highlight_bar = 2131099746;
			
			// aapt resource value: 0x7f060006
			public const int homeAsUp = 2131099654;
			
			// aapt resource value: 0x7f060063
			public const int left_bar = 2131099747;
			
			// aapt resource value: 0x7f060055
			public const int list = 2131099733;
			
			// aapt resource value: 0x7f060002
			public const int listMode = 2131099650;
			
			// aapt resource value: 0x7f060050
			public const int load_available_posts = 2131099728;
			
			// aapt resource value: 0x7f060049
			public const int logo = 2131099721;
			
			// aapt resource value: 0x7f060067
			public const int mark = 2131099751;
			
			// aapt resource value: 0x7f06006c
			public const int menu_config = 2131099756;
			
			// aapt resource value: 0x7f06006d
			public const int menu_item_action_provider_action_bar = 2131099757;
			
			// aapt resource value: 0x7f06006e
			public const int menu_item_action_provider_overflow = 2131099758;
			
			// aapt resource value: 0x7f06006f
			public const int menu_item_share_action_provider_action_bar = 2131099759;
			
			// aapt resource value: 0x7f06006b
			public const int menu_logout = 2131099755;
			
			// aapt resource value: 0x7f06006a
			public const int menu_refresh = 2131099754;
			
			// aapt resource value: 0x7f060060
			public const int middle_bar = 2131099744;
			
			// aapt resource value: 0x7f06002e
			public const int navigation_list = 2131099694;
			
			// aapt resource value: 0x7f06002d
			public const int navigation_standard = 2131099693;
			
			// aapt resource value: 0x7f06002f
			public const int navigation_tabs = 2131099695;
			
			// aapt resource value: 0x7f060001
			public const int normal = 2131099649;
			
			// aapt resource value: 0x7f06004b
			public const int password = 2131099723;
			
			// aapt resource value: 0x7f060066
			public const int play = 2131099750;
			
			// aapt resource value: 0x7f06005b
			public const int post_content = 2131099739;
			
			// aapt resource value: 0x7f06005a
			public const int post_date = 2131099738;
			
			// aapt resource value: 0x7f06002a
			public const int radio_nav = 2131099690;
			
			// aapt resource value: 0x7f06005d
			public const int refresh_button = 2131099741;
			
			// aapt resource value: 0x7f060068
			public const int reply = 2131099752;
			
			// aapt resource value: 0x7f060061
			public const int screen_title = 2131099745;
			
			// aapt resource value: 0x7f060008
			public const int showCustom = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int showHome = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int showTitle = 2131099655;
			
			// aapt resource value: 0x7f060029
			public const int show_context_menu = 2131099689;
			
			// aapt resource value: 0x7f060027
			public const int start = 2131099687;
			
			// aapt resource value: 0x7f06004c
			public const int submit = 2131099724;
			
			// aapt resource value: 0x7f060003
			public const int tabMode = 2131099651;
			
			// aapt resource value: 0x7f06005f
			public const int testel = 2131099743;
			
			// aapt resource value: 0x7f060048
			public const int text = 2131099720;
			
			// aapt resource value: 0x7f060056
			public const int top_divider = 2131099734;
			
			// aapt resource value: 0x7f060058
			public const int top_text = 2131099736;
			
			// aapt resource value: 0x7f060064
			public const int topic_name = 2131099748;
			
			// aapt resource value: 0x7f060004
			public const int useLogo = 2131099652;
			
			// aapt resource value: 0x7f060059
			public const int user_nick = 2131099737;
			
			// aapt resource value: 0x7f060057
			public const int user_photo = 2131099735;
			
			// aapt resource value: 0x7f06004a
			public const int username = 2131099722;
			
			// aapt resource value: 0x7f060000
			public const int wrap_content = 2131099648;
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0a0000
			public const int abs__max_action_buttons = 2131361792;
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int abs__action_bar_home = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int abs__action_bar_tab = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int abs__action_bar_tab_bar_view = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int abs__action_bar_title_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int abs__action_menu_item_layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int abs__action_menu_layout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int abs__action_mode_bar = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int abs__action_mode_close_item = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int abs__activity_chooser_view = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int abs__activity_chooser_view_list_item = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int abs__dialog_title_holo = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int abs__list_menu_item_checkbox = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int abs__list_menu_item_icon = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int abs__list_menu_item_layout = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int abs__list_menu_item_radio = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int abs__popup_menu_item_layout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int abs__screen_action_bar = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int abs__screen_action_bar_overlay = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int abs__screen_simple = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int abs__screen_simple_overlay_action_mode = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int action_modes = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int collapsible_edittext = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int Config = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int context_menus = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int custom_view = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int feature_toggles = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int iprogress = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int list_navigation = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int Login = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int NextPostFooter = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int overlay = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int Post = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int PostItem = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int preferences = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int PreviousPostsHeader = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int progress = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int RefreshFooter = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int settings_action_provider = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int sherlock_spinner_dropdown_item = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int sherlock_spinner_item = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int SimpleList = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int SimpleListItem = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int tab_custom_view = 2130903082;
			
			// aapt resource value: 0x7f03002b
			public const int tab_navigation = 2130903083;
			
			// aapt resource value: 0x7f03002c
			public const int text = 2130903084;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0e0000
			public const int action_bar_selected = 2131623936;
			
			// aapt resource value: 0x7f0e0001
			public const int options_menu = 2131623937;
			
			// aapt resource value: 0x7f0e0002
			public const int options_menu_action = 2131623938;
			
			// aapt resource value: 0x7f0e0003
			public const int settings_action_provider = 2131623939;
			
			// aapt resource value: 0x7f0e0004
			public const int share_action_provider = 2131623940;
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int errodeconexao = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int fimdalista = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int proxpost = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int robot = 2131034115;
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0b0000
			public const int abs__action_bar_home_description = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int abs__action_bar_up_description = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int abs__action_menu_overflow_description = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int abs__action_mode_done = 2131427331;
			
			// aapt resource value: 0x7f0b0005
			public const int abs__activity_chooser_view_dialog_title_default = 2131427333;
			
			// aapt resource value: 0x7f0b0004
			public const int abs__activity_chooser_view_see_all = 2131427332;
			
			// aapt resource value: 0x7f0b0007
			public const int abs__activitychooserview_choose_application = 2131427335;
			
			// aapt resource value: 0x7f0b0006
			public const int abs__share_action_provider_share_with = 2131427334;
			
			// aapt resource value: 0x7f0b0008
			public const int abs__shareactionprovider_share_with = 2131427336;
			
			// aapt resource value: 0x7f0b0009
			public const int abs__shareactionprovider_share_with_application = 2131427337;
			
			// aapt resource value: 0x7f0b0039
			public const int action_bar_share_with = 2131427385;
			
			// aapt resource value: 0x7f0b000c
			public const int action_items = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public const int action_items_content = 2131427341;
			
			// aapt resource value: 0x7f0b000e
			public const int action_modes = 2131427342;
			
			// aapt resource value: 0x7f0b000f
			public const int action_modes_content = 2131427343;
			
			// aapt resource value: 0x7f0b0010
			public const int action_modes_no_action_bar = 2131427344;
			
			// aapt resource value: 0x7f0b0013
			public const int action_providers = 2131427347;
			
			// aapt resource value: 0x7f0b0014
			public const int action_providers_content = 2131427348;
			
			// aapt resource value: 0x7f0b000b
			public const int activity_name = 2131427339;
			
			// aapt resource value: 0x7f0b0082
			public const int answer_topic_description = 2131427458;
			
			// aapt resource value: 0x7f0b005e
			public const int answer_topic_edittext_hint = 2131427422;
			
			// aapt resource value: 0x7f0b005d
			public const int answer_topic_submit_text = 2131427421;
			
			// aapt resource value: 0x7f0b0056
			public const int app_name = 2131427414;
			
			// aapt resource value: 0x7f0b000a
			public const int application_name = 2131427338;
			
			// aapt resource value: 0x7f0b0084
			public const int avatar_description = 2131427460;
			
			// aapt resource value: 0x7f0b0077
			public const int button_pause_blue_description = 2131427447;
			
			// aapt resource value: 0x7f0b0061
			public const int char_count_default_value = 2131427425;
			
			// aapt resource value: 0x7f0b0015
			public const int collapsible = 2131427349;
			
			// aapt resource value: 0x7f0b0016
			public const int collapsible_content = 2131427350;
			
			// aapt resource value: 0x7f0b0017
			public const int context_menus = 2131427351;
			
			// aapt resource value: 0x7f0b0018
			public const int context_menus_content = 2131427352;
			
			// aapt resource value: 0x7f0b0060
			public const int counter_default_value = 2131427424;
			
			// aapt resource value: 0x7f0b005b
			public const int courses_title = 2131427419;
			
			// aapt resource value: 0x7f0b005c
			public const int curriculum_units_title = 2131427420;
			
			// aapt resource value: 0x7f0b0019
			public const int custom_navigation = 2131427353;
			
			// aapt resource value: 0x7f0b001a
			public const int custom_navigation_content = 2131427354;
			
			// aapt resource value: 0x7f0b0055
			public const int default_value_edittext_preference = 2131427413;
			
			// aapt resource value: 0x7f0b0054
			public const int default_value_list_preference = 2131427412;
			
			// aapt resource value: 0x7f0b007a
			public const int delete = 2131427450;
			
			// aapt resource value: 0x7f0b001b
			public const int dialog = 2131427355;
			
			// aapt resource value: 0x7f0b003b
			public const int dialog_based_preferences = 2131427387;
			
			// aapt resource value: 0x7f0b001c
			public const int dialog_content = 2131427356;
			
			// aapt resource value: 0x7f0b0042
			public const int dialog_title_edittext_preference = 2131427394;
			
			// aapt resource value: 0x7f0b0045
			public const int dialog_title_list_preference = 2131427397;
			
			// aapt resource value: 0x7f0b0079
			public const int divider_line = 2131427449;
			
			// aapt resource value: 0x7f0b0064
			public const int empty_forum_message = 2131427428;
			
			// aapt resource value: 0x7f0b006c
			public const int error_connection_failed = 2131427436;
			
			// aapt resource value: 0x7f0b006d
			public const int error_playing = 2131427437;
			
			// aapt resource value: 0x7f0b0051
			public const int example_preference_dependency = 2131427409;
			
			// aapt resource value: 0x7f0b001d
			public const int feature_toggles = 2131427357;
			
			// aapt resource value: 0x7f0b001e
			public const int feature_toggles_content = 2131427358;
			
			// aapt resource value: 0x7f0b001f
			public const int forced_overflow = 2131427359;
			
			// aapt resource value: 0x7f0b0020
			public const int forced_overflow_content = 2131427360;
			
			// aapt resource value: 0x7f0b0068
			public const int fulano_name = 2131427432;
			
			// aapt resource value: 0x7f0b0075
			public const int image_audio_description = 2131427445;
			
			// aapt resource value: 0x7f0b003a
			public const int inline_preferences = 2131427386;
			
			// aapt resource value: 0x7f0b0021
			public const int iprogress = 2131427361;
			
			// aapt resource value: 0x7f0b0022
			public const int iprogress_content = 2131427362;
			
			// aapt resource value: 0x7f0b0081
			public const int iuvi_footer = 2131427457;
			
			// aapt resource value: 0x7f0b003c
			public const int launch_preferences = 2131427388;
			
			// aapt resource value: 0x7f0b0023
			public const int list_navigation = 2131427363;
			
			// aapt resource value: 0x7f0b0024
			public const int list_navigation_content = 2131427364;
			
			// aapt resource value: 0x7f0b0074
			public const int listen_to = 2131427444;
			
			// aapt resource value: 0x7f0b0083
			public const int loading_more_posts = 2131427459;
			
			// aapt resource value: 0x7f0b006a
			public const int locale_date_format = 2131427434;
			
			// aapt resource value: 0x7f0b0059
			public const int login_field_text = 2131427417;
			
			// aapt resource value: 0x7f0b0058
			public const int login_greeting_text = 2131427416;
			
			// aapt resource value: 0x7f0b0057
			public const int logo_description = 2131427415;
			
			// aapt resource value: 0x7f0b0066
			public const int new_topic_image_description = 2131427430;
			
			// aapt resource value: 0x7f0b0070
			public const int next = 2131427440;
			
			// aapt resource value: 0x7f0b007c
			public const int no_conection = 2131427452;
			
			// aapt resource value: 0x7f0b006b
			public const int no_new_posts = 2131427435;
			
			// aapt resource value: 0x7f0b0025
			public const int overlay = 2131427365;
			
			// aapt resource value: 0x7f0b0026
			public const int overlay_content = 2131427366;
			
			// aapt resource value: 0x7f0b005a
			public const int password_field_text = 2131427418;
			
			// aapt resource value: 0x7f0b007f
			public const int password_hint = 2131427455;
			
			// aapt resource value: 0x7f0b006f
			public const int pause = 2131427439;
			
			// aapt resource value: 0x7f0b006e
			public const int play = 2131427438;
			
			// aapt resource value: 0x7f0b0062
			public const int post_list_forum_name_placeholder = 2131427426;
			
			// aapt resource value: 0x7f0b0085
			public const int post_title = 2131427461;
			
			// aapt resource value: 0x7f0b0027
			public const int preference = 2131427367;
			
			// aapt resource value: 0x7f0b003d
			public const int preference_attributes = 2131427389;
			
			// aapt resource value: 0x7f0b0028
			public const int preference_content = 2131427368;
			
			// aapt resource value: 0x7f0b0071
			public const int prev = 2131427441;
			
			// aapt resource value: 0x7f0b0029
			public const int progress = 2131427369;
			
			// aapt resource value: 0x7f0b002a
			public const int progress_content = 2131427370;
			
			// aapt resource value: 0x7f0b005f
			public const int recod_button_description = 2131427423;
			
			// aapt resource value: 0x7f0b0087
			public const int record_image_description = 2131427463;
			
			// aapt resource value: 0x7f0b0072
			public const int recording_date = 2131427442;
			
			// aapt resource value: 0x7f0b0073
			public const int recording_duration = 2131427443;
			
			// aapt resource value: 0x7f0b0076
			public const int recording_progress_teste = 2131427446;
			
			// aapt resource value: 0x7f0b0011
			public const int share_action_providers = 2131427345;
			
			// aapt resource value: 0x7f0b0012
			public const int share_action_providers_content = 2131427346;
			
			// aapt resource value: 0x7f0b002b
			public const int simple = 2131427371;
			
			// aapt resource value: 0x7f0b002c
			public const int simple_content = 2131427372;
			
			// aapt resource value: 0x7f0b002d
			public const int split = 2131427373;
			
			// aapt resource value: 0x7f0b002f
			public const int split_action_modes = 2131427375;
			
			// aapt resource value: 0x7f0b002e
			public const int split_content = 2131427374;
			
			// aapt resource value: 0x7f0b0030
			public const int static_attach = 2131427376;
			
			// aapt resource value: 0x7f0b0031
			public const int static_attach_content = 2131427377;
			
			// aapt resource value: 0x7f0b0063
			public const int stock_person_description = 2131427427;
			
			// aapt resource value: 0x7f0b0078
			public const int stop_button_description = 2131427448;
			
			// aapt resource value: 0x7f0b0032
			public const int styled = 2131427378;
			
			// aapt resource value: 0x7f0b0033
			public const int styled_content = 2131427379;
			
			// aapt resource value: 0x7f0b0034
			public const int submenus = 2131427380;
			
			// aapt resource value: 0x7f0b0035
			public const int submenus_content = 2131427381;
			
			// aapt resource value: 0x7f0b0080
			public const int submit_button_text = 2131427456;
			
			// aapt resource value: 0x7f0b003f
			public const int summary_checkbox_preference = 2131427391;
			
			// aapt resource value: 0x7f0b0050
			public const int summary_child_preference = 2131427408;
			
			// aapt resource value: 0x7f0b0041
			public const int summary_edittext_preference = 2131427393;
			
			// aapt resource value: 0x7f0b0047
			public const int summary_intent_preference = 2131427399;
			
			// aapt resource value: 0x7f0b0044
			public const int summary_list_preference = 2131427396;
			
			// aapt resource value: 0x7f0b0049
			public const int summary_my_preference = 2131427401;
			
			// aapt resource value: 0x7f0b004c
			public const int summary_off_advanced_toggle_preference = 2131427404;
			
			// aapt resource value: 0x7f0b004b
			public const int summary_on_advanced_toggle_preference = 2131427403;
			
			// aapt resource value: 0x7f0b004e
			public const int summary_parent_preference = 2131427406;
			
			// aapt resource value: 0x7f0b0036
			public const int tab_navigation = 2131427382;
			
			// aapt resource value: 0x7f0b0038
			public const int tab_navigation_collapsed = 2131427384;
			
			// aapt resource value: 0x7f0b0037
			public const int tab_navigation_content = 2131427383;
			
			// aapt resource value: 0x7f0b0067
			public const int temp_description = 2131427431;
			
			// aapt resource value: 0x7f0b004a
			public const int title_advanced_toggle_preference = 2131427402;
			
			// aapt resource value: 0x7f0b003e
			public const int title_checkbox_preference = 2131427390;
			
			// aapt resource value: 0x7f0b004f
			public const int title_child_preference = 2131427407;
			
			// aapt resource value: 0x7f0b0040
			public const int title_edittext_preference = 2131427392;
			
			// aapt resource value: 0x7f0b0046
			public const int title_intent_preference = 2131427398;
			
			// aapt resource value: 0x7f0b0043
			public const int title_list_preference = 2131427395;
			
			// aapt resource value: 0x7f0b0048
			public const int title_my_preference = 2131427400;
			
			// aapt resource value: 0x7f0b004d
			public const int title_parent_preference = 2131427405;
			
			// aapt resource value: 0x7f0b0052
			public const int title_wifi = 2131427410;
			
			// aapt resource value: 0x7f0b0053
			public const int title_wifi_settings = 2131427411;
			
			// aapt resource value: 0x7f0b0065
			public const int topics_title = 2131427429;
			
			// aapt resource value: 0x7f0b007d
			public const int try_again = 2131427453;
			
			// aapt resource value: 0x7f0b0069
			public const int unloaded_posts_count = 2131427433;
			
			// aapt resource value: 0x7f0b007e
			public const int username_hint = 2131427454;
			
			// aapt resource value: 0x7f0b0088
			public const int view_holder_tag = 2131427464;
			
			// aapt resource value: 0x7f0b007b
			public const int warning_image_description = 2131427451;
			
			// aapt resource value: 0x7f0b0086
			public const int x = 2131427462;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0c0033
			public const int DialogWindowTitle_Sherlock = 2131492915;
			
			// aapt resource value: 0x7f0c0034
			public const int DialogWindowTitle_Sherlock_Light = 2131492916;
			
			// aapt resource value: 0x7f0c0047
			public const int Sherlock___TextAppearance_Small = 2131492935;
			
			// aapt resource value: 0x7f0c004a
			public const int Sherlock___Theme = 2131492938;
			
			// aapt resource value: 0x7f0c004c
			public const int Sherlock___Theme_DarkActionBar = 2131492940;
			
			// aapt resource value: 0x7f0c004d
			public const int Sherlock___Theme_Dialog = 2131492941;
			
			// aapt resource value: 0x7f0c004b
			public const int Sherlock___Theme_Light = 2131492939;
			
			// aapt resource value: 0x7f0c0001
			public const int Sherlock___Widget_ActionBar = 2131492865;
			
			// aapt resource value: 0x7f0c0016
			public const int Sherlock___Widget_ActionMode = 2131492886;
			
			// aapt resource value: 0x7f0c001e
			public const int Sherlock___Widget_ActivityChooserView = 2131492894;
			
			// aapt resource value: 0x7f0c0029
			public const int Sherlock___Widget_Holo_DropDownItem = 2131492905;
			
			// aapt resource value: 0x7f0c0026
			public const int Sherlock___Widget_Holo_ListView = 2131492902;
			
			// aapt resource value: 0x7f0c0023
			public const int Sherlock___Widget_Holo_Spinner = 2131492899;
			
			// aapt resource value: 0x7f0c0045
			public const int TextAppearance_Sherlock_DialogWindowTitle = 2131492933;
			
			// aapt resource value: 0x7f0c0046
			public const int TextAppearance_Sherlock_Light_DialogWindowTitle = 2131492934;
			
			// aapt resource value: 0x7f0c0049
			public const int TextAppearance_Sherlock_Light_Small = 2131492937;
			
			// aapt resource value: 0x7f0c0040
			public const int TextAppearance_Sherlock_Light_Widget_PopupMenu_Large = 2131492928;
			
			// aapt resource value: 0x7f0c0042
			public const int TextAppearance_Sherlock_Light_Widget_PopupMenu_Small = 2131492930;
			
			// aapt resource value: 0x7f0c0048
			public const int TextAppearance_Sherlock_Small = 2131492936;
			
			// aapt resource value: 0x7f0c0035
			public const int TextAppearance_Sherlock_Widget_ActionBar_Menu = 2131492917;
			
			// aapt resource value: 0x7f0c0038
			public const int TextAppearance_Sherlock_Widget_ActionBar_Subtitle = 2131492920;
			
			// aapt resource value: 0x7f0c0039
			public const int TextAppearance_Sherlock_Widget_ActionBar_Subtitle_Inverse = 2131492921;
			
			// aapt resource value: 0x7f0c0036
			public const int TextAppearance_Sherlock_Widget_ActionBar_Title = 2131492918;
			
			// aapt resource value: 0x7f0c0037
			public const int TextAppearance_Sherlock_Widget_ActionBar_Title_Inverse = 2131492919;
			
			// aapt resource value: 0x7f0c003c
			public const int TextAppearance_Sherlock_Widget_ActionMode_Subtitle = 2131492924;
			
			// aapt resource value: 0x7f0c003d
			public const int TextAppearance_Sherlock_Widget_ActionMode_Subtitle_Inverse = 2131492925;
			
			// aapt resource value: 0x7f0c003a
			public const int TextAppearance_Sherlock_Widget_ActionMode_Title = 2131492922;
			
			// aapt resource value: 0x7f0c003b
			public const int TextAppearance_Sherlock_Widget_ActionMode_Title_Inverse = 2131492923;
			
			// aapt resource value: 0x7f0c0044
			public const int TextAppearance_Sherlock_Widget_DropDownItem = 2131492932;
			
			// aapt resource value: 0x7f0c003e
			public const int TextAppearance_Sherlock_Widget_PopupMenu = 2131492926;
			
			// aapt resource value: 0x7f0c003f
			public const int TextAppearance_Sherlock_Widget_PopupMenu_Large = 2131492927;
			
			// aapt resource value: 0x7f0c0041
			public const int TextAppearance_Sherlock_Widget_PopupMenu_Small = 2131492929;
			
			// aapt resource value: 0x7f0c0043
			public const int TextAppearance_Sherlock_Widget_TextView_SpinnerItem = 2131492931;
			
			// aapt resource value: 0x7f0c005a
			public const int Theme_Mobilis = 2131492954;
			
			// aapt resource value: 0x7f0c004e
			public const int Theme_Sherlock = 2131492942;
			
			// aapt resource value: 0x7f0c0056
			public const int Theme_Sherlock_Dialog = 2131492950;
			
			// aapt resource value: 0x7f0c0053
			public const int Theme_Sherlock_ForceOverflow = 2131492947;
			
			// aapt resource value: 0x7f0c004f
			public const int Theme_Sherlock_Light = 2131492943;
			
			// aapt resource value: 0x7f0c0050
			public const int Theme_Sherlock_Light_DarkActionBar = 2131492944;
			
			// aapt resource value: 0x7f0c0055
			public const int Theme_Sherlock_Light_DarkActionBar_ForceOverflow = 2131492949;
			
			// aapt resource value: 0x7f0c0057
			public const int Theme_Sherlock_Light_Dialog = 2131492951;
			
			// aapt resource value: 0x7f0c0054
			public const int Theme_Sherlock_Light_ForceOverflow = 2131492948;
			
			// aapt resource value: 0x7f0c0052
			public const int Theme_Sherlock_Light_NoActionBar = 2131492946;
			
			// aapt resource value: 0x7f0c0051
			public const int Theme_Sherlock_NoActionBar = 2131492945;
			
			// aapt resource value: 0x7f0c0058
			public const int Theme_Styled = 2131492952;
			
			// aapt resource value: 0x7f0c0000
			public const int Widget = 2131492864;
			
			// aapt resource value: 0x7f0c005b
			public const int Widget_Mobilis_ActionBar = 2131492955;
			
			// aapt resource value: 0x7f0c0002
			public const int Widget_Sherlock_ActionBar = 2131492866;
			
			// aapt resource value: 0x7f0c0003
			public const int Widget_Sherlock_ActionBar_Solid = 2131492867;
			
			// aapt resource value: 0x7f0c000a
			public const int Widget_Sherlock_ActionBar_TabBar = 2131492874;
			
			// aapt resource value: 0x7f0c000d
			public const int Widget_Sherlock_ActionBar_TabText = 2131492877;
			
			// aapt resource value: 0x7f0c0007
			public const int Widget_Sherlock_ActionBar_TabView = 2131492871;
			
			// aapt resource value: 0x7f0c0010
			public const int Widget_Sherlock_ActionButton = 2131492880;
			
			// aapt resource value: 0x7f0c0012
			public const int Widget_Sherlock_ActionButton_CloseMode = 2131492882;
			
			// aapt resource value: 0x7f0c0014
			public const int Widget_Sherlock_ActionButton_Overflow = 2131492884;
			
			// aapt resource value: 0x7f0c0017
			public const int Widget_Sherlock_ActionMode = 2131492887;
			
			// aapt resource value: 0x7f0c001f
			public const int Widget_Sherlock_ActivityChooserView = 2131492895;
			
			// aapt resource value: 0x7f0c0021
			public const int Widget_Sherlock_Button_Small = 2131492897;
			
			// aapt resource value: 0x7f0c002a
			public const int Widget_Sherlock_DropDownItem_Spinner = 2131492906;
			
			// aapt resource value: 0x7f0c0004
			public const int Widget_Sherlock_Light_ActionBar = 2131492868;
			
			// aapt resource value: 0x7f0c0005
			public const int Widget_Sherlock_Light_ActionBar_Solid = 2131492869;
			
			// aapt resource value: 0x7f0c0006
			public const int Widget_Sherlock_Light_ActionBar_Solid_Inverse = 2131492870;
			
			// aapt resource value: 0x7f0c000b
			public const int Widget_Sherlock_Light_ActionBar_TabBar = 2131492875;
			
			// aapt resource value: 0x7f0c000c
			public const int Widget_Sherlock_Light_ActionBar_TabBar_Inverse = 2131492876;
			
			// aapt resource value: 0x7f0c000e
			public const int Widget_Sherlock_Light_ActionBar_TabText = 2131492878;
			
			// aapt resource value: 0x7f0c000f
			public const int Widget_Sherlock_Light_ActionBar_TabText_Inverse = 2131492879;
			
			// aapt resource value: 0x7f0c0008
			public const int Widget_Sherlock_Light_ActionBar_TabView = 2131492872;
			
			// aapt resource value: 0x7f0c0009
			public const int Widget_Sherlock_Light_ActionBar_TabView_Inverse = 2131492873;
			
			// aapt resource value: 0x7f0c0011
			public const int Widget_Sherlock_Light_ActionButton = 2131492881;
			
			// aapt resource value: 0x7f0c0013
			public const int Widget_Sherlock_Light_ActionButton_CloseMode = 2131492883;
			
			// aapt resource value: 0x7f0c0015
			public const int Widget_Sherlock_Light_ActionButton_Overflow = 2131492885;
			
			// aapt resource value: 0x7f0c0018
			public const int Widget_Sherlock_Light_ActionMode = 2131492888;
			
			// aapt resource value: 0x7f0c0019
			public const int Widget_Sherlock_Light_ActionMode_Inverse = 2131492889;
			
			// aapt resource value: 0x7f0c0020
			public const int Widget_Sherlock_Light_ActivityChooserView = 2131492896;
			
			// aapt resource value: 0x7f0c0022
			public const int Widget_Sherlock_Light_Button_Small = 2131492898;
			
			// aapt resource value: 0x7f0c002b
			public const int Widget_Sherlock_Light_DropDownItem_Spinner = 2131492907;
			
			// aapt resource value: 0x7f0c001b
			public const int Widget_Sherlock_Light_ListPopupWindow = 2131492891;
			
			// aapt resource value: 0x7f0c0028
			public const int Widget_Sherlock_Light_ListView_DropDown = 2131492904;
			
			// aapt resource value: 0x7f0c001d
			public const int Widget_Sherlock_Light_PopupMenu = 2131492893;
			
			// aapt resource value: 0x7f0c002d
			public const int Widget_Sherlock_Light_PopupWindow_ActionMode = 2131492909;
			
			// aapt resource value: 0x7f0c002f
			public const int Widget_Sherlock_Light_ProgressBar = 2131492911;
			
			// aapt resource value: 0x7f0c0031
			public const int Widget_Sherlock_Light_ProgressBar_Horizontal = 2131492913;
			
			// aapt resource value: 0x7f0c0025
			public const int Widget_Sherlock_Light_Spinner_DropDown_ActionBar = 2131492901;
			
			// aapt resource value: 0x7f0c001a
			public const int Widget_Sherlock_ListPopupWindow = 2131492890;
			
			// aapt resource value: 0x7f0c0027
			public const int Widget_Sherlock_ListView_DropDown = 2131492903;
			
			// aapt resource value: 0x7f0c001c
			public const int Widget_Sherlock_PopupMenu = 2131492892;
			
			// aapt resource value: 0x7f0c002c
			public const int Widget_Sherlock_PopupWindow_ActionMode = 2131492908;
			
			// aapt resource value: 0x7f0c002e
			public const int Widget_Sherlock_ProgressBar = 2131492910;
			
			// aapt resource value: 0x7f0c0030
			public const int Widget_Sherlock_ProgressBar_Horizontal = 2131492912;
			
			// aapt resource value: 0x7f0c0024
			public const int Widget_Sherlock_Spinner_DropDown_ActionBar = 2131492900;
			
			// aapt resource value: 0x7f0c0032
			public const int Widget_Sherlock_TextView_SpinnerItem = 2131492914;
			
			// aapt resource value: 0x7f0c0059
			public const int Widget_Styled_ActionBar = 2131492953;
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences = 2130968576;
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SherlockActionBar = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130772026,
					2130772027,
					2130772028,
					2130772029,
					2130772030,
					2130772031,
					2130772032,
					2130772033,
					2130772034,
					2130772035,
					2130772036,
					2130772037,
					2130772038};
			
			// aapt resource value: 2
			public const int SherlockActionBar_background = 2;
			
			// aapt resource value: 3
			public const int SherlockActionBar_backgroundSplit = 3;
			
			// aapt resource value: 12
			public const int SherlockActionBar_backgroundStacked = 12;
			
			// aapt resource value: 13
			public const int SherlockActionBar_customNavigationLayout = 13;
			
			// aapt resource value: 7
			public const int SherlockActionBar_displayOptions = 7;
			
			// aapt resource value: 5
			public const int SherlockActionBar_divider = 5;
			
			// aapt resource value: 4
			public const int SherlockActionBar_height = 4;
			
			// aapt resource value: 14
			public const int SherlockActionBar_homeLayout = 14;
			
			// aapt resource value: 10
			public const int SherlockActionBar_icon = 10;
			
			// aapt resource value: 16
			public const int SherlockActionBar_indeterminateProgressStyle = 16;
			
			// aapt resource value: 18
			public const int SherlockActionBar_itemPadding = 18;
			
			// aapt resource value: 11
			public const int SherlockActionBar_logo = 11;
			
			// aapt resource value: 6
			public const int SherlockActionBar_navigationMode = 6;
			
			// aapt resource value: 17
			public const int SherlockActionBar_progressBarPadding = 17;
			
			// aapt resource value: 15
			public const int SherlockActionBar_progressBarStyle = 15;
			
			// aapt resource value: 9
			public const int SherlockActionBar_subtitle = 9;
			
			// aapt resource value: 1
			public const int SherlockActionBar_subtitleTextStyle = 1;
			
			// aapt resource value: 8
			public const int SherlockActionBar_title = 8;
			
			// aapt resource value: 0
			public const int SherlockActionBar_titleTextStyle = 0;
			
			public static int[] SherlockActionMenuItemView = new int[] {
					16843071};
			
			// aapt resource value: 0
			public const int SherlockActionMenuItemView_android_minWidth = 0;
			
			public static int[] SherlockActionMode = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 2
			public const int SherlockActionMode_background = 2;
			
			// aapt resource value: 3
			public const int SherlockActionMode_backgroundSplit = 3;
			
			// aapt resource value: 4
			public const int SherlockActionMode_height = 4;
			
			// aapt resource value: 1
			public const int SherlockActionMode_subtitleTextStyle = 1;
			
			// aapt resource value: 0
			public const int SherlockActionMode_titleTextStyle = 0;
			
			public static int[] SherlockActivityChooserView = new int[] {
					16842964,
					2130772047,
					2130772048};
			
			// aapt resource value: 0
			public const int SherlockActivityChooserView_android_background = 0;
			
			// aapt resource value: 2
			public const int SherlockActivityChooserView_expandActivityOverflowButtonDrawable = 2;
			
			// aapt resource value: 1
			public const int SherlockActivityChooserView_initialActivityCount = 1;
			
			public static int[] SherlockMenuGroup = new int[] {
					16842766,
					16842960,
					16843156,
					16843230,
					16843231,
					16843232};
			
			// aapt resource value: 5
			public const int SherlockMenuGroup_android_checkableBehavior = 5;
			
			// aapt resource value: 0
			public const int SherlockMenuGroup_android_enabled = 0;
			
			// aapt resource value: 1
			public const int SherlockMenuGroup_android_id = 1;
			
			// aapt resource value: 3
			public const int SherlockMenuGroup_android_menuCategory = 3;
			
			// aapt resource value: 4
			public const int SherlockMenuGroup_android_orderInCategory = 4;
			
			// aapt resource value: 2
			public const int SherlockMenuGroup_android_visible = 2;
			
			public static int[] SherlockMenuItem = new int[] {
					16842754,
					16842766,
					16842960,
					16843014,
					16843156,
					16843230,
					16843231,
					16843233,
					16843234,
					16843235,
					16843236,
					16843237,
					16843375,
					16843481,
					16843515,
					16843516,
					16843657};
			
			// aapt resource value: 14
			public const int SherlockMenuItem_android_actionLayout = 14;
			
			// aapt resource value: 16
			public const int SherlockMenuItem_android_actionProviderClass = 16;
			
			// aapt resource value: 15
			public const int SherlockMenuItem_android_actionViewClass = 15;
			
			// aapt resource value: 9
			public const int SherlockMenuItem_android_alphabeticShortcut = 9;
			
			// aapt resource value: 11
			public const int SherlockMenuItem_android_checkable = 11;
			
			// aapt resource value: 3
			public const int SherlockMenuItem_android_checked = 3;
			
			// aapt resource value: 1
			public const int SherlockMenuItem_android_enabled = 1;
			
			// aapt resource value: 0
			public const int SherlockMenuItem_android_icon = 0;
			
			// aapt resource value: 2
			public const int SherlockMenuItem_android_id = 2;
			
			// aapt resource value: 5
			public const int SherlockMenuItem_android_menuCategory = 5;
			
			// aapt resource value: 10
			public const int SherlockMenuItem_android_numericShortcut = 10;
			
			// aapt resource value: 12
			public const int SherlockMenuItem_android_onClick = 12;
			
			// aapt resource value: 6
			public const int SherlockMenuItem_android_orderInCategory = 6;
			
			// aapt resource value: 13
			public const int SherlockMenuItem_android_showAsAction = 13;
			
			// aapt resource value: 7
			public const int SherlockMenuItem_android_title = 7;
			
			// aapt resource value: 8
			public const int SherlockMenuItem_android_titleCondensed = 8;
			
			// aapt resource value: 4
			public const int SherlockMenuItem_android_visible = 4;
			
			public static int[] SherlockMenuView = new int[] {
					2130772039,
					2130772040,
					2130772041,
					2130772042,
					2130772043,
					2130772044,
					2130772045,
					2130772046};
			
			// aapt resource value: 3
			public const int SherlockMenuView_headerBackground = 3;
			
			// aapt resource value: 1
			public const int SherlockMenuView_horizontalDivider = 1;
			
			// aapt resource value: 4
			public const int SherlockMenuView_itemBackground = 4;
			
			// aapt resource value: 6
			public const int SherlockMenuView_itemIconDisabledAlpha = 6;
			
			// aapt resource value: 0
			public const int SherlockMenuView_itemTextAppearance = 0;
			
			// aapt resource value: 7
			public const int SherlockMenuView_preserveIconSpacing = 7;
			
			// aapt resource value: 2
			public const int SherlockMenuView_verticalDivider = 2;
			
			// aapt resource value: 5
			public const int SherlockMenuView_windowAnimationStyle = 5;
			
			public static int[] SherlockSpinner = new int[] {
					16842927,
					16843125,
					16843126,
					16843131,
					16843362,
					16843436,
					16843437,
					16843759};
			
			// aapt resource value: 5
			public const int SherlockSpinner_android_dropDownHorizontalOffset = 5;
			
			// aapt resource value: 1
			public const int SherlockSpinner_android_dropDownSelector = 1;
			
			// aapt resource value: 6
			public const int SherlockSpinner_android_dropDownVerticalOffset = 6;
			
			// aapt resource value: 4
			public const int SherlockSpinner_android_dropDownWidth = 4;
			
			// aapt resource value: 0
			public const int SherlockSpinner_android_gravity = 0;
			
			// aapt resource value: 2
			public const int SherlockSpinner_android_popupBackground = 2;
			
			// aapt resource value: 7
			public const int SherlockSpinner_android_popupPromptView = 7;
			
			// aapt resource value: 3
			public const int SherlockSpinner_android_prompt = 3;
			
			public static int[] SherlockTheme = new int[] {
					16842839,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024,
					2130772025};
			
			// aapt resource value: 52
			public const int SherlockTheme_absForceOverflow = 52;
			
			// aapt resource value: 9
			public const int SherlockTheme_actionBarDivider = 9;
			
			// aapt resource value: 10
			public const int SherlockTheme_actionBarItemBackground = 10;
			
			// aapt resource value: 8
			public const int SherlockTheme_actionBarSize = 8;
			
			// aapt resource value: 6
			public const int SherlockTheme_actionBarSplitStyle = 6;
			
			// aapt resource value: 5
			public const int SherlockTheme_actionBarStyle = 5;
			
			// aapt resource value: 2
			public const int SherlockTheme_actionBarTabBarStyle = 2;
			
			// aapt resource value: 1
			public const int SherlockTheme_actionBarTabStyle = 1;
			
			// aapt resource value: 3
			public const int SherlockTheme_actionBarTabTextStyle = 3;
			
			// aapt resource value: 7
			public const int SherlockTheme_actionBarWidgetTheme = 7;
			
			// aapt resource value: 38
			public const int SherlockTheme_actionButtonStyle = 38;
			
			// aapt resource value: 37
			public const int SherlockTheme_actionDropDownStyle = 37;
			
			// aapt resource value: 11
			public const int SherlockTheme_actionMenuTextAppearance = 11;
			
			// aapt resource value: 12
			public const int SherlockTheme_actionMenuTextColor = 12;
			
			// aapt resource value: 15
			public const int SherlockTheme_actionModeBackground = 15;
			
			// aapt resource value: 14
			public const int SherlockTheme_actionModeCloseButtonStyle = 14;
			
			// aapt resource value: 17
			public const int SherlockTheme_actionModeCloseDrawable = 17;
			
			// aapt resource value: 19
			public const int SherlockTheme_actionModePopupWindowStyle = 19;
			
			// aapt resource value: 18
			public const int SherlockTheme_actionModeShareDrawable = 18;
			
			// aapt resource value: 16
			public const int SherlockTheme_actionModeSplitBackground = 16;
			
			// aapt resource value: 13
			public const int SherlockTheme_actionModeStyle = 13;
			
			// aapt resource value: 4
			public const int SherlockTheme_actionOverflowButtonStyle = 4;
			
			// aapt resource value: 43
			public const int SherlockTheme_actionSpinnerItemStyle = 43;
			
			// aapt resource value: 51
			public const int SherlockTheme_activatedBackgroundIndicator = 51;
			
			// aapt resource value: 50
			public const int SherlockTheme_activityChooserViewStyle = 50;
			
			// aapt resource value: 0
			public const int SherlockTheme_android_windowIsFloating = 0;
			
			// aapt resource value: 20
			public const int SherlockTheme_buttonStyleSmall = 20;
			
			// aapt resource value: 36
			public const int SherlockTheme_dividerVertical = 36;
			
			// aapt resource value: 40
			public const int SherlockTheme_dropDownListViewStyle = 40;
			
			// aapt resource value: 42
			public const int SherlockTheme_dropdownListPreferredItemHeight = 42;
			
			// aapt resource value: 39
			public const int SherlockTheme_homeAsUpIndicator = 39;
			
			// aapt resource value: 49
			public const int SherlockTheme_listPopupWindowStyle = 49;
			
			// aapt resource value: 30
			public const int SherlockTheme_listPreferredItemHeightSmall = 30;
			
			// aapt resource value: 31
			public const int SherlockTheme_listPreferredItemPaddingLeft = 31;
			
			// aapt resource value: 32
			public const int SherlockTheme_listPreferredItemPaddingRight = 32;
			
			// aapt resource value: 41
			public const int SherlockTheme_popupMenuStyle = 41;
			
			// aapt resource value: 29
			public const int SherlockTheme_spinnerDropDownItemStyle = 29;
			
			// aapt resource value: 28
			public const int SherlockTheme_spinnerItemStyle = 28;
			
			// aapt resource value: 22
			public const int SherlockTheme_textAppearanceLargePopupMenu = 22;
			
			// aapt resource value: 33
			public const int SherlockTheme_textAppearanceListItemSmall = 33;
			
			// aapt resource value: 24
			public const int SherlockTheme_textAppearanceSmall = 24;
			
			// aapt resource value: 23
			public const int SherlockTheme_textAppearanceSmallPopupMenu = 23;
			
			// aapt resource value: 25
			public const int SherlockTheme_textColorPrimary = 25;
			
			// aapt resource value: 26
			public const int SherlockTheme_textColorPrimaryDisableOnly = 26;
			
			// aapt resource value: 27
			public const int SherlockTheme_textColorPrimaryInverse = 27;
			
			// aapt resource value: 45
			public const int SherlockTheme_windowActionBar = 45;
			
			// aapt resource value: 46
			public const int SherlockTheme_windowActionBarOverlay = 46;
			
			// aapt resource value: 47
			public const int SherlockTheme_windowActionModeOverlay = 47;
			
			// aapt resource value: 21
			public const int SherlockTheme_windowContentOverlay = 21;
			
			// aapt resource value: 34
			public const int SherlockTheme_windowMinWidthMajor = 34;
			
			// aapt resource value: 35
			public const int SherlockTheme_windowMinWidthMinor = 35;
			
			// aapt resource value: 44
			public const int SherlockTheme_windowNoTitle = 44;
			
			// aapt resource value: 48
			public const int SherlockTheme_windowSplitActionBar = 48;
			
			private Styleable()
			{
			}
		}
	}
}
