//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobilis
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int course_list_idle = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int course_list_pressed = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int text_color = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int yellow_highlight = 2130968576;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int course_list_selector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int login_gradient = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int logo_solar = 2130837507;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int footer = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int footer_text = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int highlight_bar = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int left_bar = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int list = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int logo = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int middle_bar = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int password = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int screen_title = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int submit = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int testel = 2131099654;
			
			// aapt resource value: 0x7f06000c
			public const int topic_name = 2131099660;
			
			// aapt resource value: 0x7f060001
			public const int username = 2131099649;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int SimpleList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SimpleListItem = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05002c
			public const int answer_topic_description = 2131034156;
			
			// aapt resource value: 0x7f050008
			public const int answer_topic_edittext_hint = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int answer_topic_submit_text = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f05002e
			public const int avatar_description = 2131034158;
			
			// aapt resource value: 0x7f050021
			public const int button_pause_blue_description = 2131034145;
			
			// aapt resource value: 0x7f05000b
			public const int char_count_default_value = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int counter_default_value = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int courses_title = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int curriculum_units_title = 2131034118;
			
			// aapt resource value: 0x7f050024
			public const int delete = 2131034148;
			
			// aapt resource value: 0x7f050023
			public const int divider_line = 2131034147;
			
			// aapt resource value: 0x7f05000e
			public const int empty_forum_message = 2131034126;
			
			// aapt resource value: 0x7f050016
			public const int error_connection_failed = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int error_playing = 2131034135;
			
			// aapt resource value: 0x7f050012
			public const int fulano_name = 2131034130;
			
			// aapt resource value: 0x7f05001f
			public const int image_audio_description = 2131034143;
			
			// aapt resource value: 0x7f05002b
			public const int iuvi_footer = 2131034155;
			
			// aapt resource value: 0x7f05001e
			public const int listen_to = 2131034142;
			
			// aapt resource value: 0x7f05002d
			public const int loading_more_posts = 2131034157;
			
			// aapt resource value: 0x7f050014
			public const int locale_date_format = 2131034132;
			
			// aapt resource value: 0x7f050003
			public const int login_field_text = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int login_greeting_text = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int logo_description = 2131034113;
			
			// aapt resource value: 0x7f050010
			public const int new_topic_image_description = 2131034128;
			
			// aapt resource value: 0x7f05001a
			public const int next = 2131034138;
			
			// aapt resource value: 0x7f050026
			public const int no_conection = 2131034150;
			
			// aapt resource value: 0x7f050015
			public const int no_new_posts = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int not_loaded_posts_count = 2131034131;
			
			// aapt resource value: 0x7f050004
			public const int password_field_text = 2131034116;
			
			// aapt resource value: 0x7f050029
			public const int password_hint = 2131034153;
			
			// aapt resource value: 0x7f050019
			public const int pause = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int play = 2131034136;
			
			// aapt resource value: 0x7f05000c
			public const int post_list_forum_name_placeholder = 2131034124;
			
			// aapt resource value: 0x7f05002f
			public const int post_title = 2131034159;
			
			// aapt resource value: 0x7f05001b
			public const int prev = 2131034139;
			
			// aapt resource value: 0x7f050009
			public const int recod_button_description = 2131034121;
			
			// aapt resource value: 0x7f050031
			public const int record_image_description = 2131034161;
			
			// aapt resource value: 0x7f05001c
			public const int recording_date = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int recording_duration = 2131034141;
			
			// aapt resource value: 0x7f050020
			public const int recording_progress_teste = 2131034144;
			
			// aapt resource value: 0x7f05000d
			public const int stock_person_description = 2131034125;
			
			// aapt resource value: 0x7f050022
			public const int stop_button_description = 2131034146;
			
			// aapt resource value: 0x7f05002a
			public const int submit_button_text = 2131034154;
			
			// aapt resource value: 0x7f050011
			public const int temp_description = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public const int topics_title = 2131034127;
			
			// aapt resource value: 0x7f050027
			public const int try_again = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int username_hint = 2131034152;
			
			// aapt resource value: 0x7f050025
			public const int warning_image_description = 2131034149;
			
			// aapt resource value: 0x7f050030
			public const int x = 2131034160;
			
			private String()
			{
			}
		}
	}
}
